### ISSUE TITLE
Static IP Address configurations are not supported

### ISSUE THREAD

**Issue by mkostersitz** [Azure/aksArc#14]
**Describe the bug**
When using static IP addresses for virtual machines and the host nodes deployment fails.

**To Reproduce**

**Expected behavior**
Static IP addresses to work

**Screenshots**

**Environment (please complete the following information):**
- AKS-HCI Version (i.e. Public Preview 1)
- Kubernetes Version (i.e. 1.18.6)

**Additional context**

**Collect log files**
- From a PowerShell Admin window run **Collect-AksHciLogs**
- If you are running into issues with the deployment wizard in Windows Admin Center, run 
**Get-SMEUILogs.ps1** from the machine hosting Windows Admin Center.”

**Comment by madhanrm** [comment]
can we close this
