### ISSUE TITLE
AKS HCI Auto Deployment Fails

### ISSUE THREAD

**Issue by V-HMabrouk** [Azure/aksArc#191]
When I try to create the VM with an Azure Resource Manager JSON Template referenced [here](https://github.com/Azure/aks-hci/tree/main/eval/autodeploy#deploying-the-azure-vm), I receive the following error:

`{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"VMExtensionProvisioningError","message":"VM has reported a failure when processing extension 'InstallAksHci'. Error message: \"Command execution finished, but failed because it returned a non-zero exit code of: '1'. The command had an error output of: 'Connecting to remote server AKSHCIHost001 failed with the following error message : Access is denied. For more \r\ninformation, see the about_Remote_Troubleshooting Help topic.\r\nAt C:\\Packages\\Plugins\\Microsoft.Compute.CustomScriptExtension\\1.10.12\\Downloads...' For more information, check the instance view by executing Get-AzVmssVm or Get-AzVm (https://aka.ms/GetAzVm). These commands can be executed using CloudShell (https://aka.ms/CloudShell)\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSEWindowsTroubleshoot "}]}`

The deployment parameters are as follows:
`{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "virtualMachineName": {
            "value": "AKSHCIHost001"
        },
        "virtualMachineSize": {
            "value": "Standard_E16s_v4"
        },
        "virtualMachineGeneration": {
            "value": "Generation 2"
        },
        "domainName": {
            "value": "akshci.local"
        },
        "dataDiskType": {
            "value": "StandardSSD_LRS"
        },
        "dataDiskSize": {
            "value": "32"
        },
        "adminUsername": {
            "value": "AzureUser"
        },
        "adminPassword": {
            "value": null
        },
        "customRdpPort": {
            "value": "3389"
        },
        "akS-HCIAppId": {
            "value": "<SERVICE-PRINCIPAL-APP-ID>"
        },
        "akS-HCIAppSecret": {
            "value": null
        },
        "akS-HCINetworking": {
            "value": "DHCP"
        },
        "kubernetesVersion": {
            "value": "Match Management Cluster"
        },
        "controlPlaneNodes": {
            "value": 1
        },
        "controlPlaneNodeSize": {
            "value": "Standard_A4_v2 (4vCPU, 8GB RAM)"
        },
        "loadBalancerSize": {
            "value": "Standard_A4_v2 (4vCPU, 8GB RAM)"
        },
        "linuxWorkerNodes": {
            "value": 3
        },
        "linuxWorkerNodeSize": {
            "value": "Standard_K8S3_v1 (4vCPU, 6GB RAM)"
        },
        "windowsWorkerNodes": {
            "value": 0
        },
        "windowsWorkerNodeSize": {
            "value": "Standard_K8S3_v1 (4vCPU, 6GB RAM)"
        },
        "installWindowsAdminCenter": {
            "value": "No"
        },
        "enableArcIntegration": {
            "value": "Yes"
        },
        "autoShutdownStatus": {
            "value": "Enabled"
        },
        "autoShutdownTime": {
            "value": "22:00"
        },
        "autoShutdownTimeZone": {
            "value": "UTC"
        },
        "alreadyHaveAWindowsServerLicense": {
            "value": "No"
        }
    }
}`

Does anyone know why this might be happening? 
Thanks in advance.

**Comment by leslielin-5** [comment]
Hello, the eval guide was recently updated here: https://docs.microsoft.com/en-us/azure-stack/aks-hci/aks-hci-evaluation-guide
Could you please use this instead and let us know if the same error occurs? Thanks.

**Comment by leslielin-5** [comment]
Please find the latest guidance to deploy ARM on AKS on Azure Local (previously known as AKS on Azure Stack HCI). https://learn.microsoft.com/en-us/azure/aks/hybrid/resource-manager-quickstart
