### ISSUE TITLE
Lifecycle management of AKS clusters on Azure Stack HCI or Windows Server via Azure Portal

### ISSUE THREAD

**Issue by PragyaDw** [Azure/aksArc#246]
Enables you to use familiar tools like the Azure portal, Azure CLI and Azure Resource Manager templates to create and manage your AKS hybrid clusters running on Azure Stack HCI and Windows Server. Azure Arc is automatically enabled on all your AKS hybrid clusters so you can use your Azure AD identity for connecting to your clusters from anywhere. This ensures your developers and application operators can provision and configure Kubernetes clusters in accordance with company policies. We’ve also simplified the end-to-end security posture for your AKS hybrid clusters through Microsoft Defender for Cloud.

**Comment by parameshbabu** [comment]
This feature is supported as part of 23H2 release and full lifecycle management is supported on AKS on HCI 23H2. No plans to support this on 22H2 or WS. Closing.
