### ISSUE TITLE
Reduce the download size for cluster upgrade

### ISSUE THREAD

**Issue by PragyaDw** [Azure/aksArc#259]
Speeding up cluster upgrade time will ensure that these customers are able to adopt new releases in time as well as reduce the upgrade failure rate for deployments in low latent environments.

**Comment by Elektronenvolt** [comment]
We don't run into issues with the current download sizes of base images, but I've noticed that downloads getting much slower / aborted at the second / third cluster behind the same public IP.

**Comment by scooley** [comment]
Sharing as FYI - WS22 vhd as a container base is much smaller :) (like 30% smaller)
