### ISSUE TITLE
Appliance rolls back to its previous working state version on upgrade failure

### ISSUE THREAD

**Issue by PragyaDw** [Azure/aksArc#265]

**Comment by aunghsi1** [comment]
လောကတစ်ခွင် မိမိတို့ကျွမ်းကျင်သော လောကိအတတ်များဖြင့် လူသား ကမ္မာအလှဆင်ကြပါဆို့လို့ တိုက်တွန်းနှိုးဆော်လိုက်ရပါသည်ခင်ဗျာ

**Comment by aunghsi1** [comment]
Hello
