### ISSUE TITLE
Set-AksHciRegistration is not saving SPN secret in AzureRmContext.json causes install-AksHci fail

### ISSUE THREAD

**Issue by HassanAlmanasrah** [Azure/aksArc#282]
when I run **Install-AksHci -verbose** its failing with the below error 
Message              : Install-AksHci - Unable to get ServicePrincipalSecret from Azure Context.

the failure is in specific with command Invoke-KvaCtlWithAzureContext , checking the AzureRmContext.json file, it doesn't contain SPN secret any more in it.

AKSHybrid version: 1.0.15.11104

**Comment by HassanAlmanasrah** [comment]
as workaround, added the SPN secret in the file manually which passed this issue

**Comment by apluchik** [comment]
@HassanAlmanasrah could you please provide the steps you ran to hit this issue?

**Comment by HassanAlmanasrah** [comment]
@apluchik here are the steps:

1.
$vnet = New-AksHciNetworkSetting  -name `
-vswitchName  `
-vipPoolStart  `
-vipPoolEnd  `
-vlanID 

2.
Set-AksHciConfig -imageDir $imageDir `
-workingDir $workingDir `
-cloudConfigLocation $cloudConfigLocation `
-vnet $vnet `
-version "1.0.13.10907" `
-cloudservicecidr 

3. useSPN
Set-AksHciRegistration -SubscriptionId $subscription -ResourceGroupName $resource_group -TenantId $tenantID -Credential $credential

4.
$VerbosePreference = "Continue"
Install-AksHci -verbose

Step 3 is going to create AzureRmContext.json file in path c:\users\user\.Azure
usually this file contains both SPN and its secret , which will be used during installation in step 4. Recently, this file doesn't contain "ServicePrincipalSecret", which causes deployment failure. As a workaround, When I added the SPN secret manually , it  passes the failed step. So, my explanation that command Set-AksHciRegistration is not saving the secret in the generated file like in the past, could be newer version for the module was released recently?

**Comment by cblackuk** [comment]
Having the exact same issue:
```powershell
Unable to get ServicePrincipalSecret from Azure Context.


TestName       : Validate KVA
Category       : KVA
TestResult     : Failed
Details        : Unable to get ServicePrincipalSecret from Azure Context.
Recommendation :
```

Steps to repro:
```powershell
$TenantId = "xxxx"
$Sub = "xxxx"
$RG = "xxx"
$SPNClientId = "xxxx"
$SPNClientSecret = "xxxx"
[SecureString] $SPNClientSecretSecure = ConvertTo-SecureString $SPNClientSecret -AsPlainText -Force

$Creds = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $SPNClientId, $SPNClientSecretSecure

Set-AksHciRegistration -SubscriptionId $Sub -TenantId $TenantId -ResourceGroupName $RG -Credential $Creds
```

Also tried with -SkipLogin and -ApplicationID, same result

**Comment by cblackuk** [comment]
Update:
Better fix :-)
```powershell
Import-Module -Name "Az.Accounts" -RequiredVersion 2.6.0
```

Also, the reason why `2.11.2` is there is because it is one of the dependencies for https://www.powershellgallery.com/packages/Az.StackHCI/1.4.2 which most likely already installed on the HCI node :)

Dependencies
[Az.Accounts](https://www.powershellgallery.com/packages/Az.Accounts/) (>= 2.11.2)

Hopefully that helps somebody :-)

**Comment by shobhit-coder** [comment]
Thanks @cblackuk . I have been following your comments over the past few days which helped me past my troubles. I was planning to put the latest comment similar to yours, but it is already there :)

**Comment by cblackuk** [comment]
> Thanks @cblackuk . I have been following your comments over the past few days which helped me past my troubles. I was planning to put the latest comment similar to yours, but it is already there :)

Glad it helped :-)

**Comment by igomaa** [comment]
I have tried what @mbrat2005  found, and worked , with  Az.Accounts version 2.12.1 only .

**Comment by mrhoads** [comment]
I wanted to add that I also was able to get this to work only after following what @mbrat2005 described with adding the ServicePrincipalSecret under the account's ExtendedProperties object

**Comment by cblackuk** [comment]
I wonder if something has changed? Was a new module release or what is the delta? :-)

I think I will be looking at it again in a few weeks, so I guess I will find out :-)

BTW Can you paste a dummy JSON here where you are adding the Secret, please? @mrhoads

**Comment by cblackuk** [comment]
I see now - the https://www.powershellgallery.com/packages/Az.StackHCI/1.4.3  has changed and the dependency is now:
Dependencies
[Az.Accounts](https://www.powershellgallery.com/packages/Az.Accounts/) (>= 2.12.0)

Also https://www.powershellgallery.com/packages/AksHci/1.1.68 has been bumped a bunch of times... and yet this is not fixed ;-)

**Comment by mrhoads** [comment]
It's the line "ServicePrincipalSecret": "<manually added the SP secret>" that I manually added
```
{
  "DefaultContextKey": "my context info here",
  "EnvironmentTable": {},
  "Contexts": {
    "<my subscription name etc.": {
      "Account": {
        "Id": "<my id>",
        "Credential": null,
        "Type": "ServicePrincipal",
        "TenantMap": {},
        "ExtendedProperties": {
          "Subscriptions": "<subscription id>",
          "Tenants": "<tenant id>",
          "ServicePrincipalSecret": "<manually added the SP secret>"

        }
      },`
```

**Comment by cblackuk** [comment]
> It's the line "ServicePrincipalSecret": "" that I manually added
> 
> ```
> {
>   "DefaultContextKey": "my context info here",
>   "EnvironmentTable": {},
>   "Contexts": {
>     "<my subscription name etc.": {
>       "Account": {
>         "Id": "<my id>",
>         "Credential": null,
>         "Type": "ServicePrincipal",
>         "TenantMap": {},
>         "ExtendedProperties": {
>           "Subscriptions": "<subscription id>",
>           "Tenants": "<tenant id>",
>           "ServicePrincipalSecret": "<manually added the SP secret>"
> 
>         }
>       },`
> ```

Thank you :-)

**Comment by madhanrm** [comment]
https://github.com/Azure/aksArc/issues/379#issuecomment-2492849855
