### ISSUE TITLE
Ability to update proxy certs as a day 2 operation.

### ISSUE THREAD

**Issue by PragyaDw** [Azure/aksArc#339]
An AKS cluster needs to trust other on-premises resources such as the container registry. This feature helps to add a certificate chain of trust (root, intermediate and lead certificates) with a public key, for the endpoints the cluster is expected to trust and allow communication. The certificates are added on the Linux hosts.

**Comment by PragyaDw** [comment]
[](https://learn.microsoft.com/en-us/azure/aks/hybrid/update-certificate-bundle)

**Comment by parameshbabu** [comment]
https://learn.microsoft.com/en-us/azure/aks/hybrid/update-certificate-bundle
