### ISSUE TITLE
Enable-AksHciArcConnection shows warning about GetServicePrincipals have insufficient privileges to enable custom locations

### ISSUE THREAD

**Issue by dineshba** [Azure/aksArc#375]
**Describe the bug**
Enable-AksHciArcConnection can connect AKS cluster to Azure but shows the warning below when the customer uses service principal for authentication:
```
WARNING: Error occurred while executing GetServicePrincipals
Code: Authorization_RequestDenied
Message: Insufficient privileges to complete the operation.
RequestId: <removed>
DateTimeStamp: Wed, 29 May 2024 08:04:07 GMT
HttpStatusCode: Forbidden
HttpStatusDescription: Forbidden
HttpResponseStatus: Completed
WARNING: Custom locations has not been enabled on the AKS-HCI cluster. To enable custom locations manually, visit aka.ms/enable-custom-location
```

## Known Issue:
The current behavior of the Arc Onboarding is to, by default enable Custom Locations.  To be able to do this, the GetServicePrincipals action is performed in the context of the logged in Azure user.  And, if the user (or SPN) does not have sufficient permissions to be able to do this, this command throw Warning that these permissions don't exist and so the CL (Custom Locations) feature will not be enabled.

If the customer does not want CL to be enabled, they can safely ignore this warning, as this does not affect cluster onboarding to Arc.

On the other hand, if they do need CL to be enabled, they need to grant the necessary permission to the user (or SPN).

**Comment by parameshbabu** [comment]
Thanks @dineshba for calling this out. This is a known issue as it depends on the access rights available to the SPN in use. The Custom Location requires higher privileges and the auto enabling is done on best case basis.
