### ISSUE TITLE
Capability to use Azure Workload Identity (AZWI) out of the box

### ISSUE THREAD

**Issue by chris8205** [Azure/aksArc#377]
Hi,

we need the capability to use AZWI out of the box on AzureStack HCI AKS...
There exists manuals how to do this on selfmanaged K8S but AKS is sealed, so please implement this fastest possible, in the AzureStack HCI AKS.

best whises

Chris

**Comment by abhilashaagarwala** [comment]
Hi @chris8205! Workload identity federation is currently on the roadmap for AKS on Azure Stack HCI 23H2. Once we have the capability, we will update the release notes here - https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-whats-new-23h2

**Comment by oocx** [comment]
Hi @abhilashaagarwala ,

I don't see Workload Identity Federation in the roadmap. Was ist removed from 23H2? Is it still on the roadmap for a future release?

Thanks
Mathias

**Comment by leslielin-5** [comment]
Hi @chris8205! workload identify federation is available for public preview. Follow the instructions here and share your feedback with us! https://learn.microsoft.com/en-us/azure/aks/hybrid/workload-identity

**Comment by leslielin-5** [comment]
closing as the feature is launched. Please open another ticket if there's feedback for us. Thanks!

**Comment by dotTrench** [comment]
Hello! Is there any updates available on getting this feature out of preview into GA?
