### ISSUE TITLE
Support for stretch clusters.

### ISSUE THREAD

**Issue by andersonshen** [Azure/aksArc#71]
If all the AS-HCI of the primary site cannot be recovered, how to do the disaster recovery of AKS on the secondary site 
Can AKS support HCI stretched cluster?

**Comment by bajorgensen** [comment]
Also getting this request from customers. Ideally it would entail a redundant site aware control plane with automatic failover in a site failure scenario.

**Comment by lisaattheedge** [comment]
Is there any update on this?

**Comment by eponerine** [comment]
I feel like this request vibes with https://github.com/Azure/aks-hci/issues/76

**Comment by CHTL0107** [comment]
AKS is it supported on stretched cluster Azure stack HCI??? anyone can told us??

**Comment by scooley** [comment]
Updated to stretch cluster support for easier tracking.

**Comment by CHTL0107** [comment]
AKS on HCI stretched cluster is not supported
