### ISSUE TITLE
kubectl delete node does not remove workernode VM

### ISSUE THREAD

**Issue by mkostersitz** [Azure/aksArc#8]
Current Behavior
Installed single Linux node configuration. After  a while, the worker node went into 'NotReady' mode after being 'Ready'. I still cannot figure out what actions caused it to happen.
I used the commandline to scale the cluster to two nodes.  A new node was spun up, but the command did not terminate. This was probably because as stated in #1, the original node had gone into 'NotReady' state.
Used kubectl delete node to delete the node. It did not show up in the kubectl get nodes command but the VM continued to run. 

Expected Behavior
Kubectl delete node would delete the node and associated VM
K8s would detect that node was deleted and automatically spin up new node.

**Comment by parameshbabu** [comment]
Closing legacy/outdated issues
